# syntax=docker/dockerfile:1.7

ARG DOTNET_SDK_IMAGE=mcr.microsoft.com/dotnet/sdk:8.0
ARG DOTNET_RUNTIME_IMAGE=mcr.microsoft.com/dotnet/aspnet:8.0
ARG BUILD_CONFIGURATION=Release

FROM ${DOTNET_SDK_IMAGE} AS restore
WORKDIR /src

ENV DOTNET_NOLOGO=true \
    DOTNET_CLI_TELEMETRY_OPTOUT=true \
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

# Copy the full tree for PR DOCKER-1 so locked restore can validate the
# committed packages.lock.json files generated by ./eng/restore-locks.sh.
# A later optimization PR can split this into smaller COPY layers after the
# lock files are present in every checkout.
COPY . .

RUN --mount=type=cache,id=treehammock-nuget,target=/root/.nuget/packages \
    ./eng/check-locks.sh && \
    dotnet restore treehammock.sln --locked-mode

FROM restore AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

RUN --mount=type=cache,id=treehammock-nuget,target=/root/.nuget/packages \
    dotnet build treehammock.sln \
      --configuration "$BUILD_CONFIGURATION" \
      --no-restore \
      -p:ContinuousIntegrationBuild=true

FROM build AS unit-test
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

RUN --mount=type=cache,id=treehammock-nuget,target=/root/.nuget/packages \
    dotnet test treehammock.Tests/treehammock.Tests.csproj \
      --configuration "$BUILD_CONFIGURATION" \
      --no-build \
      --no-restore \
      --filter "FullyQualifiedName~treehammock.Tests.Unit" \
      --logger "trx;LogFileName=treehammock-unit-tests.trx"

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

RUN --mount=type=cache,id=treehammock-nuget,target=/root/.nuget/packages \
    dotnet publish treehammock.csproj \
      --configuration "$BUILD_CONFIGURATION" \
      --no-build \
      -p:UseAppHost=false \
      --output /app/publish

FROM ${DOTNET_RUNTIME_IMAGE} AS api
WORKDIR /app

LABEL org.opencontainers.image.title="treehammock API" \
      org.opencontainers.image.description="Container runtime image for the treehammock ASP.NET Core API"

ENV ASPNETCORE_ENVIRONMENT=Container \
    DOTNET_ENVIRONMENT=Container \
    ASPNETCORE_URLS=http://+:5001

COPY --from=publish /app/publish .

EXPOSE 5001

ENTRYPOINT ["dotnet", "treehammock.dll"]
