services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: ContainerReverseProxy
      DOTNET_ENVIRONMENT: ContainerReverseProxy
      HostingSettings__UseForwardedHeaders: "true"
      HostingSettings__ForwardLimit: "1"
      HostingSettings__RequireHeaderSymmetry: "true"
      HostingSettings__TrustAllForwardedHeaderProxies: "true"
