namespace treehammock.Tests.Infrastructure;

public static class TestConfiguration
{
    public static Dictionary<string, string?> ValidSettings()
    {
        return new Dictionary<string, string?>
        {
            ["DatabaseSettings:servers"] = "localhost",
            ["DatabaseSettings:database"] = "treehammock_tests",
            ["DatabaseSettings:userId"] = "treehammock",
            ["DatabaseSettings:password"] = "test-db-password",
            ["DatabaseSettings:lc_collation"] = "en_US.UTF-8",

            ["ActiveUserBundleSettings:servers"] = "localhost",
            ["ActiveUserBundleSettings:port"] = "6379",
            ["ActiveUserBundleSettings:database"] = "0",
            ["ActiveUserBundleSettings:clientName"] = "treehammock-tests",
            ["ActiveUserBundleSettings:allowAdmin"] = "false",
            ["ActiveUserBundleSettings:reconnectRetryPolicy"] = "5000",
            ["ActiveUserBundleSettings:abortOnConnectFail"] = "false",
            ["ActiveUserBundleSettings:password"] = string.Empty,

            ["TwoFactorSessionBundleSettings:servers"] = "localhost",
            ["TwoFactorSessionBundleSettings:port"] = "6379",
            ["TwoFactorSessionBundleSettings:database"] = "1",
            ["TwoFactorSessionBundleSettings:clientName"] = "treehammock-tests-2fa",
            ["TwoFactorSessionBundleSettings:allowAdmin"] = "false",
            ["TwoFactorSessionBundleSettings:reconnectRetryPolicy"] = "5000",
            ["TwoFactorSessionBundleSettings:abortOnConnectFail"] = "false",
            ["TwoFactorSessionBundleSettings:password"] = string.Empty,

            ["AbuseCounterBundleSettings:servers"] = "localhost",
            ["AbuseCounterBundleSettings:port"] = "6379",
            ["AbuseCounterBundleSettings:database"] = "2",
            ["AbuseCounterBundleSettings:clientName"] = "treehammock-tests-abuse-counters",
            ["AbuseCounterBundleSettings:allowAdmin"] = "false",
            ["AbuseCounterBundleSettings:reconnectRetryPolicy"] = "5000",
            ["AbuseCounterBundleSettings:abortOnConnectFail"] = "false",
            ["AbuseCounterBundleSettings:password"] = string.Empty,
            ["AbuseCounterBundleSettings:connectTimeoutMilliseconds"] = "1000",
            ["AbuseCounterBundleSettings:asyncTimeoutMilliseconds"] = "1000",
            ["AbuseCounterBundleSettings:syncTimeoutMilliseconds"] = "1000",
            ["AbuseCounterBundleSettings:connectRetry"] = "1",

            ["SessionCacheFallbackSettings:CacheReadTimeoutMilliseconds"] = "250",
            ["SessionCacheFallbackSettings:CacheWriteTimeoutMilliseconds"] = "250",
            ["SessionCacheFallbackSettings:CacheRevokeTimeoutMilliseconds"] = "250",
            ["SessionCacheFallbackSettings:DatabaseFallbackTimeoutMilliseconds"] = "1000",

            ["AbuseControlSettings:Enabled"] = "true",
            ["AbuseControlSettings:DragonflyTimeoutMilliseconds"] = "250",
            ["AbuseControlSettings:CounterFailureMode"] = "FailClosed",
            ["AbuseControlSettings:TwoFactor:Enabled"] = "true",
            ["AbuseControlSettings:TwoFactor:MaxAttemptsPerChallenge"] = "5",
            ["AbuseControlSettings:TwoFactor:ChallengeAttemptWindowSeconds"] = "600",
            ["AbuseControlSettings:TwoFactor:CooldownSecondsAfterExhaustion"] = "900",
            ["AbuseControlSettings:TwoFactor:MaxSetupVerifyAttemptsPerAccount"] = "5",
            ["AbuseControlSettings:TwoFactor:SetupVerifyAttemptWindowSeconds"] = "600",
            ["AbuseControlSettings:TwoFactor:SetupVerifyCooldownSecondsAfterExhaustion"] = "900",
            ["AbuseControlSettings:Delivery:Enabled"] = "true",
            ["AbuseControlSettings:Delivery:MaxEmailDeliveriesPerAccountPerHour"] = "5",
            ["AbuseControlSettings:Delivery:MaxSmsDeliveriesPerAccountPerHour"] = "3",
            ["AbuseControlSettings:Delivery:MaxEmailDeliveriesPerIpPerHour"] = "20",
            ["AbuseControlSettings:Delivery:MaxSmsDeliveriesPerIpPerHour"] = "10",
            ["AbuseControlSettings:Delivery:CooldownSecondsAfterRepeatedFailures"] = "900",
            ["AbuseControlSettings:FailureCooldown:Enabled"] = "true",
            ["AbuseControlSettings:FailureCooldown:FailureThreshold"] = "5",
            ["AbuseControlSettings:FailureCooldown:WindowSeconds"] = "900",
            ["AbuseControlSettings:FailureCooldown:CooldownSeconds"] = "900",
            ["AbuseControlSettings:Login:Enabled"] = "true",
            ["AbuseControlSettings:Login:MaxAttemptsPerAccountPerWindow"] = "10",
            ["AbuseControlSettings:Login:MaxAttemptsPerIdentifierPerWindow"] = "10",
            ["AbuseControlSettings:Login:MaxAttemptsPerIpPerWindow"] = "50",
            ["AbuseControlSettings:Login:CaptchaChallengeEnabled"] = "false",
            ["AbuseControlSettings:Login:CaptchaChallengeAfterAttempts"] = "5",
            ["AbuseControlSettings:Login:WindowSeconds"] = "900",
            ["AbuseControlSettings:Login:CooldownSeconds"] = "900",
            ["AbuseControlSettings:PasswordReset:Enabled"] = "true",
            ["AbuseControlSettings:PasswordReset:MaxRequestsPerAccountPerHour"] = "3",
            ["AbuseControlSettings:PasswordReset:MaxRequestsPerIdentifierPerHour"] = "5",
            ["AbuseControlSettings:PasswordReset:MaxRequestsPerIpPerHour"] = "20",
            ["AbuseControlSettings:PasswordReset:MaxTokenVerificationAttemptsPerResetId"] = "5",
            ["AbuseControlSettings:PasswordReset:TokenVerificationAttemptWindowSeconds"] = "900",
            ["AbuseControlSettings:PasswordReset:MaxTwoFactorProofAttemptsPerResetId"] = "5",
            ["AbuseControlSettings:PasswordReset:TwoFactorProofAttemptWindowSeconds"] = "900",
            ["AbuseControlSettings:PasswordReset:MaxFinalizeAttemptsPerResetId"] = "5",
            ["AbuseControlSettings:PasswordReset:FinalizeAttemptWindowSeconds"] = "900",
            ["AbuseControlSettings:PasswordReset:CooldownSecondsAfterExhaustion"] = "900",
            ["AbuseControlSettings:AccountUnlock:Enabled"] = "true",
            ["AbuseControlSettings:AccountUnlock:MaxVerifyAttemptsPerToken"] = "5",
            ["AbuseControlSettings:AccountUnlock:MaxVerifyAttemptsPerIp"] = "25",
            ["AbuseControlSettings:AccountUnlock:VerifyAttemptWindowSeconds"] = "900",
            ["AbuseControlSettings:AccountUnlock:CooldownSecondsAfterExhaustion"] = "900",
            ["AbuseControlSettings:AccountDelete:Enabled"] = "true",
            ["AbuseControlSettings:AccountDelete:MaxFinalizeAttemptsPerAccount"] = "5",
            ["AbuseControlSettings:AccountDelete:MaxFinalizeAttemptsPerToken"] = "5",
            ["AbuseControlSettings:AccountDelete:FinalizeAttemptWindowSeconds"] = "900",
            ["AbuseControlSettings:AccountDelete:CooldownSecondsAfterExhaustion"] = "900",
            ["AbuseControlSettings:PublicTokenVerification:Enabled"] = "true",
            ["AbuseControlSettings:PublicTokenVerification:MaxVerifyAttemptsPerToken"] = "10",
            ["AbuseControlSettings:PublicTokenVerification:MaxVerifyAttemptsPerIp"] = "100",
            ["AbuseControlSettings:PublicTokenVerification:VerifyAttemptWindowSeconds"] = "900",
            ["AbuseControlSettings:PublicTokenVerification:CooldownSecondsAfterExhaustion"] = "900",
            ["AbuseControlSettings:Activation:Enabled"] = "true",
            ["AbuseControlSettings:Activation:MaxVerifyAttemptsPerAccount"] = "5",
            ["AbuseControlSettings:Activation:MaxVerifyAttemptsPerIdentifier"] = "5",
            ["AbuseControlSettings:Activation:MaxVerifyAttemptsPerIp"] = "50",
            ["AbuseControlSettings:Activation:VerifyAttemptWindowSeconds"] = "900",
            ["AbuseControlSettings:Activation:CooldownSecondsAfterExhaustion"] = "900",
            ["AbuseControlSettings:AuthenticatedMutationIdempotency:Enabled"] = "true",
            ["AbuseControlSettings:AuthenticatedMutationIdempotency:MinKeyLength"] = "16",
            ["AbuseControlSettings:AuthenticatedMutationIdempotency:MaxKeyLength"] = "128",
            ["AbuseControlSettings:AuthenticatedMutationIdempotency:TimeoutMilliseconds"] = "25",
            ["AbuseControlSettings:AuthenticatedMutationIdempotency:InProgressTtlSeconds"] = "600",
            ["AbuseControlSettings:AuthenticatedMutationIdempotency:CompletedTtlSeconds"] = "900",

            ["JWTSettings:JsonWebTokenIssuer"] = "treehammock-tests",
            ["JWTSettings:RefreshTokenGenRetries"] = "3",
            ["JWTSettings:RefreshTokenAliveDays"] = "0",
            ["JWTSettings:RefreshTokenAliveHours"] = "1",
            ["JWTSettings:RefreshTokenAliveMinutes"] = "0",
            ["JWTSettings:RefreshTokenAliveDays_2FA"] = "0",
            ["JWTSettings:RefreshTokenAliveHours_2FA"] = "0",
            ["JWTSettings:RefreshTokenAliveMinutes_2FA"] = "2",
            ["JWTSettings:RefreshTokenAliveDays_DB"] = "7",
            ["JWTSettings:RefreshTokenAliveHours_DB"] = "0",
            ["JWTSettings:RefreshTokenAliveMinutes_DB"] = "0",
            ["JWTSettings:RefreshTokenAliveDays_Short"] = "0",
            ["JWTSettings:RefreshTokenAliveHours_Short"] = "0",
            ["JWTSettings:RefreshTokenAliveMinutes_Short"] = "15",
            ["JWTSettings:RefreshTokenBytes"] = "64",
            ["JWTSettings:RefreshWindowMinutes"] = "10",

            ["LoginSettings:PasswordRetryLimit"] = "3",
            ["LoginSettings:TwoAuthRetryLimit"] = "3",
            ["LoginSettings:TwoFactorChallengeResendCooldownSeconds"] = "30",
            ["LoginSettings:TwoFactorChallengePepper"] = "test-two-factor-pepper",
            ["LoginSettings:Argon2Iterations"] = "1",
            ["LoginSettings:Argon2MemoryUsePer"] = "8192",

            ["RegistrationSettings:MinUsernameLength"] = "3",
            ["RegistrationSettings:MaxUsernameLength"] = "30",
            ["RegistrationSettings:MinPasswordLength"] = "8",
            ["RegistrationSettings:MaxPasswordLength"] = "128",
            ["RegistrationSettings:MaxEmailAddressLength"] = "255",
            ["RegistrationSettings:AccountMetaDataRetries"] = "3",
            ["RegistrationSettings:VerifyAccountPeriodWeeks"] = "0",
            ["RegistrationSettings:VerifyAccountPeriodDays"] = "1",
            ["RegistrationSettings:VerifyAccountPeriodHours"] = "0",
            ["RegistrationSettings:EmailChangeVerifyPeriodWeeks"] = "0",
            ["RegistrationSettings:EmailChangeVerifyPeriodDays"] = "1",
            ["RegistrationSettings:EmailChangeVerifyPeriodHours"] = "0",
            ["RegistrationSettings:AccountEmailChangeVerificationBaseUrl"] = "http://localhost.test",
            ["RegistrationSettings:AccountDeleteTokenPeriodWeeks"] = "0",
            ["RegistrationSettings:AccountDeleteTokenPeriodDays"] = "1",
            ["RegistrationSettings:AccountDeleteTokenPeriodHours"] = "0",
            ["RegistrationSettings:AccountDeleteVerifyBaseUrl"] = "http://localhost.test",
            ["RegistrationSettings:DeleteRequestCooldownMinutes"] = "15",
            ["RegistrationSettings:DeleteRequestWindowHours"] = "24",
            ["RegistrationSettings:DeleteMaxRequestsPerWindow"] = "8",
            ["RegistrationSettings:DeleteMaxFinalizeFailures"] = "5",
            ["RegistrationSettings:DeleteFinalizeLockoutMinutes"] = "30",

            ["PasswordResetSettings:CodeLength"] = "8",
            ["PasswordResetSettings:CodeHashPepper"] = "test-password-reset-code-pepper",
            ["PasswordResetSettings:ExpirationMinutes"] = "2",
            ["PasswordResetSettings:MaxAttempts"] = "5",
            ["PasswordResetSettings:RequestCooldownSeconds"] = "60",
            ["PasswordResetSettings:DailyRequestLimitPerAccount"] = "5",
            ["PasswordResetSettings:DailyRequestLimitPerDestination"] = "5",
            ["PasswordResetSettings:DailyRequestLimitPerIp"] = "20",
            ["PasswordResetSettings:DailyRequestWindowHours"] = "24",
            ["PasswordResetSettings:RateLimitBlockMinutes"] = "30",
            ["PasswordResetSettings:CaptchaChallengeEnabled"] = "false",
            ["PasswordResetSettings:CaptchaChallengeAfterRequests"] = "3",

            ["SensitiveActionSettings:TokenBytes"] = "32",
            ["SensitiveActionSettings:ExpirationMinutes"] = "10",
            ["SensitiveActionSettings:ConsumeExistingTokensOnIssue"] = "true",
            ["TotpSettings:Issuer"] = "Treehammock",
            ["TotpSettings:Digits"] = "6",
            ["TotpSettings:PeriodSeconds"] = "30",
            ["TotpSettings:AllowedClockSkewSteps"] = "1",
            ["TotpSettings:HashAlgorithm"] = "SHA1",
            ["TotpSettings:SecretBytes"] = "20",
            ["TotpSettings:SecretProtectionKey"] = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=",
            ["TotpSettings:SetupIdBytes"] = "32",
            ["TotpSettings:SetupExpirationMinutes"] = "10",
            ["TotpSettings:SetupMaxAttempts"] = "5",

            ["SMTPSettings:SMTPQualifiedDomain"] = "localhost",
            ["SMTPSettings:SMTPPort"] = "1025",
            ["SMTPSettings:SMTPUsername"] = "test-smtp-user",
            ["SMTPSettings:SMTPPassword"] = "test-smtp-password",
            ["SMTPSettings:NoReplyEmailAddress"] = "noreply@localhost.test",

            ["EmailTemplateSettings:AccountVerify"] = "email_templates/AccountVerify.html",
            ["EmailTemplateSettings:AccountVerifyResend"] = "email_templates/AccountVerifyResend.html",
            ["EmailTemplateSettings:AccountEmailChangeVerify"] = "email_templates/AccountEmailChangeVerify.html",
            ["EmailTemplateSettings:AccountDeleteVerify"] = "email_templates/AccountDeleteVerify.html",
            ["EmailTemplateSettings:AccountUnlock"] = "email_templates/AccountUnlock.html",
            ["EmailTemplateSettings:TwoFactorSetup"] = "email_templates/TwoFactorSetup.html",
            ["EmailTemplateSettings:TwoFactorKeyOutbound"] = "email_templates/TwoFactorKeyOutbound.html",
            ["EmailTemplateSettings:TwoFactorDelete"] = "email_templates/TwoFactorDelete.html",
            ["EmailTemplateSettings:PasswordResetCode"] = "email_templates/PasswordResetCode.html",
            ["EmailTemplateSettings:PasswordResetSmsCode"] = "sms_templates/PasswordResetCode.txt",
            ["EmailTemplateSettings:AccountVerificationSuccessPage"] = "html_templates/account_verification/success.html",
            ["EmailTemplateSettings:AccountVerificationFailurePage"] = "html_templates/account_verification/failure.html",
            ["EmailTemplateSettings:AccountVerificationExpiredPage"] = "html_templates/account_verification/expired.html",
            ["EmailTemplateSettings:AccountVerificationAlreadyVerifiedPage"] = "html_templates/account_verification/already-verified.html",
            ["EmailTemplateSettings:SMSTwoFactorSetup"] = "email_templates/TwoFactorSetup.html",
            ["EmailTemplateSettings:SMSTwoFactorRemove"] = "email_templates/TwoFactorDelete.html",

            ["EmailSubjectSettings:AccountVerify"] = "Verify your Treehammock account",
            ["EmailSubjectSettings:AccountVerifyResend"] = "Verify your Treehammock account",
            ["EmailSubjectSettings:AccountEmailChangeVerify"] = "Verify your new email address",
            ["EmailSubjectSettings:AccountDeleteVerify"] = "Confirm account deletion",
            ["EmailSubjectSettings:AccountUnlock"] = "Unlock your Treehammock account",
            ["EmailSubjectSettings:TwoFactorSetup"] = "Confirm two-factor setup",
            ["EmailSubjectSettings:TwoFactorKeyOutbound"] = "Your Treehammock two-factor code",
            ["EmailSubjectSettings:TwoFactorDelete"] = "Confirm two-factor removal",
            ["EmailSubjectSettings:ActivationCode"] = "Your Treehammock activation code",
            ["EmailSubjectSettings:PasswordResetCode"] = "Your Treehammock password reset code",

            ["SidewalkSettings:SmsEnabled"] = "true",
            ["SidewalkSettings:AwsSnsEnabled"] = "true",
            ["SidewalkSettings:TwilioEnabled"] = "true",
            ["SidewalkSettings:SmsProviderPrimary"] = "aws",
            ["SidewalkSettings:SmsProviderSecondary"] = "twilio",
            ["SidewalkSettings:PaymentProcessorPrimary"] = "disabled-test",
            ["SidewalkSettings:SMSHardStop"] = "100",

            ["HostingSettings:ConfigureKestrel"] = "true",
            ["HostingSettings:Port"] = "5001",
            ["HostingSettings:BindAddress"] = "0.0.0.0",
            ["HostingSettings:UseHttps"] = "true",
            ["HostingSettings:Protocols"] = "Http1AndHttp2AndHttp3",
            ["HostingSettings:UseHttpsRedirection"] = "true",
            ["HostingSettings:UseForwardedHeaders"] = "false",
            ["HostingSettings:ForwardLimit"] = "1",
            ["HostingSettings:RequireHeaderSymmetry"] = "true",
            ["HostingSettings:TrustAllForwardedHeaderProxies"] = "false"
        };
    }

    public static Dictionary<string, string?> WithoutSection(string sectionName)
    {
        return ValidSettings()
            .Where(pair => !pair.Key.StartsWith(sectionName + ":", StringComparison.OrdinalIgnoreCase))
            .ToDictionary(pair => pair.Key, pair => pair.Value);
    }
}
