namespace treehammock.RiggingSupport.Status;

public enum IntraMessage
{
    SUCCESSFUL = 1,
    TOKEN_THREW_EXCEPTION_IN_VALIDATION = 1000,
    TOKEN_FAILED_VALIDATION = 1010,
    TOKEN_PASSED_VALIDATION = 1020,
    TOKEN_AT_EXPIRATION = 1040,
    TOKEN_EXPIRED_VALIDATION = 1070,
    TOKEN_VALIDATION_MALFORMED = 1090,
    AUTHENTICATION_DUPLICATE = 5000,
    AUTHENTICATION_PASSED = 5010,
    AUTHENTICATION_FAILED = 5020,
    AUTHENTICATION_BAD_PASSWORD = 5030,
    AUTHENTICATION_TWO_FACTOR_AUTH_REQUESTED = 5040,
    AUTHENTICATION_TWO_FACTOR_PASSED = 5050,
    AUTHENTICATION_TWO_FACTOR_FAILED = 5060,
    AUTHENTICATION_TWO_FACTOR_CODE_TIMEOUT = 5070,
    AUTHENTICATION_EXPIRED = 5700,
    AUTHENTICATION_REFRESHED = 5750,
    ACCOUNT_CREATION_SUCCESSED = 8000,
    ACCOUNT_CREATION_DUPLICATE_NAME = 8010,
    ACCOUNT_CREATION_FAILED = 8020,
    ACCOUNT_CREATION_PASSWORD_REQUIREMENT = 8030,
    ACCOUNT_CREATION_DUPLICATE_EMAIL = 8040,
    ACCOUNT_CREATION_VERIFICATION_PENDING = 9530,
    ACCOUNT_CREATION_VERIFICATION_FAILED = 9540,
    ACCOUNT_CREATION_VERIFICATION_EXPIRED = 9560,
    ACCOUNT_CREATION_VERIFICATION_RESENT = 9570,
    ACCOUNT_CREATION_VERIFICATION_RENEW = 9590,
    NONE = 0
}
